#
# makefile for Linux (x86, PPC, alpha ...)
#

OPTFLAGS=-g2 -fsanitize=address -fno-omit-frame-pointer
# OPTFLAGS=-g2 -fsanitize=thread -fno-omit-frame-pointer
#OPTFLAGS=-g2 -fsanitize=undefined -ftrapv -fsanitize=address -fsanitize=undefined -fno-sanitize=alignment -fno-omit-frame-pointer

ALLFLAGS=${OPTFLAGS} -pipe  \
	-DDONT_REDEFINE_NEW \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-DNDEBUG -D_REENTRANT -DENV_UNIX \
	-D_7ZIP_LARGE_PAGES \
	$(LOCAL_FLAGS)

CXX=g++
CC=gcc
CC_SHARED=-fPIC
LINK_SHARED=-fPIC -shared

LOCAL_LIBS=-lpthread
LOCAL_LIBS_DLL=$(LOCAL_LIBS) -ldl

OBJ_CRC32=$(OBJ_CRC32_C)
OBJ_AES=

