#
# makefile for Linux (x86, PPC, alpha ...)
#

OPTFLAGS=-O -s

ALLFLAGS=${OPTFLAGS} -pipe \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-DNDEBUG -D_REENTRANT -DENV_UNIX \
	-D_7ZIP_LARGE_PAGES \
	$(LOCAL_FLAGS)

CXX=/home/me/TOOLS/afl-1.94b/afl-g++
CC=/home/me/TOOLS/afl-1.94b/afl-gcc
CC_SHARED=-fPIC
LINK_SHARED=-fPIC -shared

LOCAL_LIBS=-lpthread
LOCAL_LIBS_DLL=$(LOCAL_LIBS) -ldl

OBJ_CRC32=$(OBJ_CRC32_C)
OBJ_AES=

