#
# makefile for Linux (other)
#

OPTFLAGS=-O -s

ALLFLAGS=${OPTFLAGS} -pipe \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-DNDEBUG -D_REENTRANT -DENV_UNIX \
	-D_7ZIP_LARGE_PAGES \
	$(LOCAL_FLAGS)

CXX=/home/me/BUILDROOT/buildroot-2010.11/output/staging/usr/bin/i386-unknown-linux-uclibc-g++
CC=/home/me/BUILDROOT/buildroot-2010.11/output/staging/usr/bin/i386-unknown-linux-uclibc-gcc
CC_SHARED=-fPIC
LINK_SHARED=-fPIC -shared

#LOCAL_LIBS=-L,/home/me/BUILDROOT/buildroot-2010.11/output/staging/usr/lib -Wl,-rpath,/home/me/BUILDROOT/buildroot-2010.11/output/staging/usr/lib -lpthread
LOCAL_LIBS=-lpthread
LOCAL_LIBS_DLL=$(LOCAL_LIBS) -ldl

OBJ_CRC32=$(OBJ_CRC32_C)
OBJ_AES=

