#
# makefile for Linux (x86, PPC, alpha ...)
#

OPTFLAGS=-g1

ALLFLAGS=${OPTFLAGS} -pipe \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-DNDEBUG -D_REENTRANT -DENV_UNIX \
	-D_7ZIP_LARGE_PAGES \
	$(LOCAL_FLAGS)

CXX=g++
CC=gcc
CC_SHARED=-fPIC
LINK_SHARED=-fPIC -shared

LOCAL_LIBS=-lpthread
LOCAL_LIBS_DLL=$(LOCAL_LIBS) -ldl

TOOLS=valgrind --tool=memcheck --leak-check=full --show-reachable=yes --log-file="/tmp/traces_valgrind/valgrind_%p"

OBJ_CRC32=$(OBJ_CRC32_C)
OBJ_AES=

