
OPTFLAGS=-g2 -fsanitize=undefined -ftrapv -fsanitize=address -fno-omit-frame-pointer -fno-sanitize=alignment


ALLFLAGS=-m64 ${OPTFLAGS} -pipe \
	-DDONT_REDEFINE_NEW \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-DNDEBUG -D_REENTRANT -DENV_UNIX \
	-D_7ZIP_LARGE_PAGES \
	-D_7ZIP_ASM \
	$(LOCAL_FLAGS)

CXX=clang++
CC=clang
CC_SHARED=-fPIC
LINK_SHARED=-fPIC -shared
ASM=yasm -f elf -m amd64 -Dx64

PRE_COMPILED_HEADER=StdAfx.h.gch

LOCAL_LIBS=-s -lpthread
LOCAL_LIBS_DLL=$(LOCAL_LIBS) -ldl

CPU=x64
OBJ_CRC32=$(OBJ_CRC32_x86_64)
OBJ_AES=AesOpt.o

