
OPTFLAGS=-O

# don't use -DNDEBUG in order to use MacOSX wxWidgets

ALLFLAGS=${OPTFLAGS}  \
	-mmacosx-version-min=10.4 -arch i386 \
	-DENV_MACOSX \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-D_REENTRANT -DENV_UNIX \
	-D_7ZIP_ASM \
	$(LOCAL_FLAGS)

CXX=c++
CC=cc
LINK_SHARED=-bundle
ASM=nasm -f macho

LOCAL_LIBS=-framework CoreFoundation
LOCAL_LIBS_DLL=$(LOCAL_LIBS)

CPU=x86
OBJ_CRC32=$(OBJ_CRC32_x86)
OBJ_AES=AesOpt.o

