PROG=PipeLen

# -D_USE_ASM
LOCAL_FLAGS=-I.

include ../../../makefile.machine

TARGET_FLAGS=$(CC_EXE)
LOCAL_LINK=$(LINK_EXE)
LIBS=$(LOCAL_LIBS)

# pl.o
OBJS=PipeLen.o
 

include ../../../makefile.glb

